name: Jacoco Coverage Test

on:
  pull_request:
    branches:
      ["master"]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add application-test yaml secrets
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ github.workspace }}/src/test/resources/application-test.yaml
        env:
          spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          spring.security.oauth2.client.registration.google.scope: ${{ secrets.GOOGLE_SCOPE }}
          spring.security.oauth2.client.registration.google.redirect-uri: ${{ secrets.GOOGLE_REDIRECT_URI_TEST }}

      - name: Test with Gradle
        run: ./gradlew build --info test

      - name: Jacoco Test Coverage Report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 'Jacoco Test Coverage Report'
          paths: ${{ github.workspace }}/build/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-covorage-overall: 0
          min-coverage-changed-files: 0